version: '3.9'

volumes:
  postgres-gca-data: {}

services:
  gca-db:
    container_name: gca-db
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_googleclassroom
    volumes:
      - postgres-gca-data:/var/lib/postgresql/data
    networks:
      - gca-network
  gca-flyway:
    container_name: gca-flyway
    image: boxfuse/flyway:5.2.4
    command: -url=jdbc:postgresql://gca-db:5432/db_googleclassroom?user=postgres&password=postgres -locations='filesystem:/opt/scripts' -outOfOrder=true migrate
    volumes:
      - ./scripts:/opt/scripts
    depends_on:
      - gca-db
    restart: on-failure
    networks:
      - gca-network
networks:
  gca-network:
    external:
      name: gca-network
    driver: bridge