version: "3.1"

volumes:
  grafana-data: {}
  postgres-data: {}
services:
  gca-grafana:
    container_name: gca-grafana
    restart: always
    image: grafana/grafana
    ports:
      - '3000:3000'
    volumes:
      # Data persistency
      # sudo mkdir -p /srv/docker/influxdb/data
      - grafana-data:/var/lib/grafana
    networks:
      - gca-network
    depends_on:
      - 'gca-prom'
  gca-prom:
    container_name: gca-prometheus
    image: gca-prometheus
    build:
      context: .
      dockerfile: ./prometheus/Dockerfile
    ports:
      - 9090:9090
    networks:
      - gca-network
  gca_rabbitmq:
    container_name: gca_rabbitmq
    image: rabbitmq:3.7-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=bitnami
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - gca-network
networks:
  gca-network:
    external:
      name: gca-network
    driver: bridge