version: '3.9'

volumes:
  postgres-gca-data: {}

services:
  gca-db:
    container_name: gca-db
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_googleclassroom
    volumes:
      - postgres-gca-data:/var/lib/postgresql/data
    networks:
      - gca-network
networks:
  gca-network:
    external:
      name: gca-network
    driver: bridge