{
 "title": "GCA Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Monitoramento", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Quantidade de sincronizações (24h)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(sincronizacao_quantidade)" }
   ]
  },
  {
   "title": "Total de sincronizações (24h)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(sincronizacao_quantidade)" }
   ]
  },
  {
   "title": "Quantidade de erros (24h)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sincronizacao_quantidade_erros)"
    }
   ]
  },
  {
   "title": "Total de erros (24h)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(sincronizacao_quantidade_erros)"
    }
   ]
  },
  { "title": "Casos de uso", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Quantidade de erros por caso de uso (24hr)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sincronizacao_quantidade_erros" },
    {}
   ]
  },
  {
   "title": "Tempo médio de execução por caso de uso",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sincronizacao_duracao_segundos_sum/sincronizacao_duracao_segundos_count"
    }
   ]
  }
 ]
}